// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module template_ip_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 4
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW
    output template_ip_reg_pkg::template_ip_reg2hw_t reg2hw,  // Write
    input template_ip_reg_pkg::template_ip_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import template_ip_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [ AW-1:0] reg_addr;
  logic [ DW-1:0] reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [ DW-1:0] reg_rdata;
  logic           reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic ctrl_en_wd;
  logic ctrl_en_we;
  logic ctrl_clr_wd;
  logic ctrl_clr_we;
  logic [31:0] din_0_qs;
  logic [31:0] din_0_wd;
  logic din_0_we;
  logic [31:0] din_1_qs;
  logic [31:0] din_1_wd;
  logic din_1_we;
  logic [31:0] result_qs;

  // Register instances
  // R[ctrl]: V(False)

  //   F[en]: 0:0
  prim_subreg #(
      .DW      (1),
      .SWACCESS("WO"),
      .RESVAL  (1'h0)
  ) u_ctrl_en (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ctrl_en_we),
      .wd(ctrl_en_wd),

      // from internal hardware
      .de(hw2reg.ctrl.en.de),
      .d (hw2reg.ctrl.en.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.ctrl.en.q),

      .qs()
  );


  //   F[clr]: 1:1
  prim_subreg #(
      .DW      (1),
      .SWACCESS("WO"),
      .RESVAL  (1'h0)
  ) u_ctrl_clr (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(ctrl_clr_we),
      .wd(ctrl_clr_wd),

      // from internal hardware
      .de(hw2reg.ctrl.clr.de),
      .d (hw2reg.ctrl.clr.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.ctrl.clr.q),

      .qs()
  );


  // R[din_0]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_din_0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(din_0_we),
      .wd(din_0_wd),

      // from internal hardware
      .de(hw2reg.din_0.de),
      .d (hw2reg.din_0.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.din_0.q),

      // to register interface (read)
      .qs(din_0_qs)
  );


  // R[din_1]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_din_1 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(din_1_we),
      .wd(din_1_wd),

      // from internal hardware
      .de(hw2reg.din_1.de),
      .d (hw2reg.din_1.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.din_1.q),

      // to register interface (read)
      .qs(din_1_qs)
  );


  // R[result]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_result (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.result.de),
      .d (hw2reg.result.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.result.q),

      // to register interface (read)
      .qs(result_qs)
  );




  logic [3:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == TEMPLATE_IP_CTRL_OFFSET);
    addr_hit[1] = (reg_addr == TEMPLATE_IP_DIN_0_OFFSET);
    addr_hit[2] = (reg_addr == TEMPLATE_IP_DIN_1_OFFSET);
    addr_hit[3] = (reg_addr == TEMPLATE_IP_RESULT_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(TEMPLATE_IP_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(TEMPLATE_IP_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(TEMPLATE_IP_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(TEMPLATE_IP_PERMIT[3] & ~reg_be)))));
  end

  assign ctrl_en_we = addr_hit[0] & reg_we & !reg_error;
  assign ctrl_en_wd = reg_wdata[0];

  assign ctrl_clr_we = addr_hit[0] & reg_we & !reg_error;
  assign ctrl_clr_wd = reg_wdata[1];

  assign din_0_we = addr_hit[1] & reg_we & !reg_error;
  assign din_0_wd = reg_wdata[31:0];

  assign din_1_we = addr_hit[2] & reg_we & !reg_error;
  assign din_1_wd = reg_wdata[31:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = '0;
        reg_rdata_next[1] = '0;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = din_0_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = din_1_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = result_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module template_ip_reg_top_intf #(
    parameter  int AW = 4,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    // To HW
    output template_ip_reg_pkg::template_ip_reg2hw_t reg2hw,  // Write
    input template_ip_reg_pkg::template_ip_hw2reg_t hw2reg,  // Read
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)



  template_ip_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg2hw,  // Write
      .hw2reg,  // Read
      .devmode_i
  );

endmodule


